CREATE TABLE t_course_1(
	course_id		BIGINT		DEFAULT 0	PRIMARY KEY	COMMENT '主键',
	course_name		VARCHAR(50)	DEFAULT ''	NOT NULL	COMMENT '课程名称',
	course_desc		VARCHAR(100)	DEFAULT ''	NOT NULL 	COMMENT '课程描述',
	course_status		INT		DEFAULT 0	NOT NULL	COMMENT '课程状态',	
	create_time		TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL	COMMENT '创建时间',
	last_update_time	TIMESTAMP	DEFAULT	CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL	COMMENT '最后修改时间' 	 
) COMMENT '课程表1';


CREATE TABLE t_user(
	user_id			BIGINT		DEFAULT 0 	PRIMARY KEY	COMMENT '主键',
	user_name		VARCHAR(50)	DEFAULT ''	NOT NULL	COMMENT '用户名称',
	user_status		INT		DEFAULT 0	NOT NULL	COMMENT '用户状态',
	create_time		TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL 	COMMENT '创建时间',
	last_update_time	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL	COMMENT '最后修改时间'
) COMMENT '用户表';

CREATE TABLE t_dict(
	dict_id			BIGINT		DEFAULT 0 	PRIMARY KEY	COMMENT '主键',
	dict_key		VARCHAR(20)	DEFAULT ''	NOT NULL	COMMENT '字典key',
	dict_value		VARCHAR(50)	DEFAULT ''	NOT NULL	COMMENT '字典value',
	dict_status		INT 		DEFAULT 0	NOT NULL 	COMMENT '字典状态',
	create_time 		TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL	COMMENT '创建时间',
	last_update_time	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '最后修改时间'
) COMMENT '公共字典表';

CREATE TABLE t_order(
	order_id		BIGINT		DEFAULT 0	PRIMARY KEY 	COMMENT '主键',
	order_cout		INT		DEFAULT 0	NOT NULL	COMMENT '课程数量',
	order_price		DECIMAL		DEFAULT 0	NOT NULL	COMMENT '订单总金额',
	student_id		BIGINT		DEFAULT 0	NOT NULL 	COMMENT '学生Id',
	pay_type		INT		DEFAULT 0	NOT NULL	COMMENT '支付方式',
	pay_id			BIGINT		DEFAULT 0 	NOT NULL	COMMENT '支付Id',
	order_status		INT 		DEFAULT 0	NOT NULL	COMMENT '订单状态',
	create_time		TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL	COMMENT '创建时间',
	last_update_time	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '最后修改时间'
) COMMENT '订单表';






















